### ISSUE TITLE
[WildFly] 'Run As > Run on Server  > Manually define server'  selection causes multiple NPE

### ISSUE THREAD

**Issue by lak-proddev** [jbosstools/jbosstools-server#586]
STEPS:
1. Create any new web project.
2. Right click on project >Run As > Run on Server  > Manually define server
3. Couple of NPE  are logging. 
See attached log for more information.

[JBoss_NPE.txt](https://github.com/jbosstools/jbosstools-server/files/2289901/JBoss_NPE.txt)

**Comment by lak-proddev** [comment]
Thanks for the  fix

**Comment by robstryker** [comment]
Fixed it
