### ISSUE TITLE
[Wildfly] Changing web port causes failing server start

### ISSUE THREAD

**Issue by lak-proddev** [jbosstools/jbosstools-server#587]
STEPS:
1.Create a new wildfly 12.x server.
2.Change the  default port number (Example 8090).

![image](https://user-images.githubusercontent.com/39690425/44143961-5d095002-a0a3-11e8-924c-abdf19408cbf.png)

3.Now ,restart the server. 
4 Server state is  never changing from `starting`  to `started`. Even the server console states that the server is started.

**Comment by lak-proddev** [comment]
So, the only way to change manually by editing `standalone.xml` ?

**Comment by robstryker** [comment]
![jbt_587](https://user-images.githubusercontent.com/630383/44346168-4e77ed00-a463-11e8-97b0-970c7ee3b28b.png)

If you expand the xml configuration in the servers view, you can edit arbitrary xpaths from a given file like standalone.xml.  So if there's some xpath you change often, this can help.

**Comment by lak-proddev** [comment]
okay, thanks for the clarification.

**Comment by robstryker** [comment]
Closing this issue.
