### ISSUE TITLE
[Wildfly] No `WildFly 14`  WTP server adapter available

### ISSUE THREAD

**Issue by lak-proddev** [jbosstools/jbosstools-server#591]
The new version of Wildfly 14.x server  is available. Which is fully JavaEE8 compatible. 
http://wildfly.org/downloads

We need to provide new server adapter for 14.x

**Comment by lak-proddev** [comment]
Thank you very much for adding the new adapter with in one working day :)

I can see two issues while working on

1. Unable deploy the `JavaEE8` EAR projects. 
As per the Wildfly 14.x  release notes,It's fully `JavaEE8` compatible right ?
http://wildfly.org/news/2018/08/30/WildFly14-Final-Released/

![image](https://user-images.githubusercontent.com/39690425/45171638-87181480-b220-11e8-917f-2432e4fdeee2.png)

2.Download link is not enabled.

![image](https://user-images.githubusercontent.com/39690425/45171833-16252c80-b221-11e8-9475-2c724119092a.png)

**Comment by robstryker** [comment]
Thanks for the bug-checks! 

Can you open two new issues for this? Sorry to ask you to do the work for me, but it'd be really helpful!

**Comment by lak-proddev** [comment]
It's okay.will file separate one's.
