### ISSUE TITLE
[Wildfly]Download link is not enabled for Wildfly 14.x 

### ISSUE THREAD

**Issue by lak-proddev** [jbosstools/jbosstools-server#596]
Download link is not enabled for Wildfly 14.x

![image](https://user-images.githubusercontent.com/39690425/45171833-16252c80-b221-11e8-9475-2c724119092a.png)

**Comment by robstryker** [comment]
Fixed by https://github.com/jboss-developer/jboss-stacks/commit/e49d9e973e8f43acff70d0ec616470186217b8e5
