### ISSUE TITLE
Latest Eclipse with Java 17 - Wildfly deployment error

### ISSUE THREAD

**Issue by davidsedlar** [jbosstools/jbosstools-server#743]
Got this problem when upgrading to latest Eclipse with Java 17. Error occurs after the server has already started, at then end of deployment.

```
An internal error occurred during: "Updating Deployment Scanners for Server: WildFly 24+".
Could not initialize class org.wildfly.security.auth.client.DefaultAuthenticationContextProvider
```

Versions:
- Eclipse 2021-12
- Java 17 (included with Eclipse distribution `openjdk.hotspot.jre.full.win32.x86_64_17.0.0.v20211012-1059`)
- Wildfly 25.0.1 (but happens on older versions as well)

Adding this to eclipse.ini seems to fix it:
`--add-opens=java.base/java.security=ALL-UNNAMED`
PS: This was posted on https://stackoverflow.com/questions/69006687/wildfly-eclipse-deployment-scanners

Screenshot:
![image](https://user-images.githubusercontent.com/1257594/146376790-cabcc279-220a-455e-b9c5-c6253842f23a.png)

**Comment by jeffmaury** [comment]
JBoss Tools is not fully compatible with Java 17. We are working to support it for the next release that is scheduled early January 2022.

Thanks for reporting.

See https://issues.redhat.com/browse/JBIDE-28087

**Comment by davidsedlar** [comment]
Ok thanks!
