### ISSUE TITLE
No new server connectors available for more recent versions of WildFly server (versions 31+)

### ISSUE THREAD

**Issue by srivatsan-srajan** [jbosstools/jbosstools-server#804]
Testing environment:
Eclipse IDE 2024-03 JEE package
JBossTools 4.30.x.Nightly
WildFly 31.0.1.Final & WildFly 32.0.0.Final
OpenJDK 17

At the moment, its not possible to configure and use WildFly 31 and above versions in the IDE.

The WildFly 27+ connector available in the IDE supports till version 30 of WildFly. However, latest version of WildFly server (https://www.wildfly.org/downloads/) is at version 32. There is also a version 31 that has been out for a while.

If I try to use the 27+ connector and point to versions 31 and 32 of the server, I get an error like below and cannot proceed with the configuration of the server. 

![image](https://github.com/jbosstools/jbosstools-server/assets/27961837/ce7b9050-d4b8-481a-8f03-2a8b387421b9)

**Comment by robstryker** [comment]
Unfortunately, JBoss Tools is not being updated with additions for newer servers. Instead, work has moved over to https://github.com/redhat-developer/rsp-server and its various extensions (for vscode: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-server-connector   or for intellij:   https://github.com/redhat-developer/intellij-rsp/)

We also did release (or are in the process of releasing) a workaround eclipse plugin that uses the same product under the hood. You can test it out here:  https://download.jboss.org/jbosstools/photon/staging/updates/

But we will no longer be expanding or improving or updating the old WTP-style servers as part of jbosstools / webtools extensions.

**Comment by nlisker** [comment]
@robstryker Can you give more detailed instructions on the new way to interface with a WildFly server from Eclipse? The update site you gave lists the same server tools feature that exists currently:
JBoss AS, WildFly & EAP Server Tools	3.10.3.v20230714-1629
